# Generated by Django 5.1.4 on 2025-02-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='candidates/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reg_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('voter_code', models.CharField(max_length=10, unique=True)),
                ('voted_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.candidate')),
            ],
        ),
    ]
